# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        com.navid.test: DEBUG

spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # BrowserSync for livereload
    jackson:
        serialization:
            indent_output: true
    data:
        mongodb:
            uri: mongodb://localhost:27017
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: false
    rabbitmq:
        addresses: amqp://admin:admin@localhost

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

# ===================================================================
# Application specific properties
# ===================================================================

app:
    cache: # Cache configuration
        hazelcast: # Hazelcast distributed cache
            backup-count: 0
            time-to-live-seconds: 3600
            management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
                enabled: true
                update-interval: 3
                url: http://localhost:8180/hazelcast-mancenter
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: 95SK8CEJWwhvS1knPaI7R2ISXbsNz8IljFDyRym4sXCKfcKD
                # Token is valid 24 hours
                token-validity-in-seconds: 30
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific mail property, for standard properties see MailProperties
        from: test@localhost
        base-url: http://127.0.0.1:8080
